server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ec2-44-199-49-128.compute-1.amazonaws.com:5432/d7aock7g38brpf?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: aqdvycmcvlgqzr
    password: 68f79432cdbd8b392c3542bf85a0d14aaa6144b4f87ae6b64c48292c731e43f6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  security:
    oauth2:
      client:
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
        registration:
          facebook:
            clientId: 2690210574458417
            clientSecret: 95241a459aba5feaaf79e04b3ac5b138
          google:
            clientId: 192667175449-6grnc55hio5gc38lmmtcc709t3ob3opl.apps.googleusercontent.com
            clientSecret: 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


  main:
    allow-bean-definition-overriding: true

support:
  email: maihai86@gmail.com
  host: https://haimt-meta-x-exam.herokuapp.com
