server:
  port: 8443

  ssl:
    enabled: false
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: 123456
    key-store-password: 123456

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exam?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
