version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "exam"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/
    networks:
      - backend

networks:
  backend:
    driver: bridge
